### ISSUE TITLE
Automatic Geolocation identifier

### ISSUE THREAD

**Issue by redian** [redian/weather-mate#7]
When you visit using a browser which supports geolocation web api, then we should try to get the local weather automatically.
More info here: https://developer.mozilla.org/en-US/docs/Web/API/Geolocation/Using_geolocation

**Comment by abiduzz420** [comment]
Thats sounds nice. That should be primary and also user should have the option of searching some other location as well, as he may use this application to check the weather before travelling.

I looked into your code and I understood many things. I'm beginner in React so going through your code and making a sense of it gave me a lot of confidence :)

**Comment by redian** [comment]
Hello @abiduzz420 funny enough i was just working on this feature.
Just pushed a commit to fix that, feel free to have a look and 9cc7d2c737ffe3e2b06320c663ffde481f108622 
and let me know if you have any ideas for improvement.

Its already deployed give it a go: https://redian.github.io/weather-mate/

Thanks for taking your time to comment.
